apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-example-monitor
  namespace: ns1 
spec:
  endpoints:
  - interval: 30s
    port: web 
    scheme: http
  selector: 
    matchLabels:
      app: prometheus-example-app
