customization:
  runAsUser: ''
  securitySecretRef: default-ingress-cert # Sticky session
decisionCenter:
  enabled: true
  # replicaCount: 1 # default value
  replicaCount: 2
image:
  pullSecrets:
    - my-odm-docker-registry
  repository: cp.icr.io/cp/cp4a/odm
# internalDatabase:
#   persistence:
#     enabled: true
#     useDynamicProvisioning: true
#   populateSampleData: true
#   runAsUser: ''
externalDatabase:
  type: postgresql
  port: 32046
  secretCredentials: odm-db-credentials
  databaseName: ibmclouddb
  serverName: ad64635e-93e7-4285-b7ed-aac7cfda5dcc.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud
  populateSampleData: true
license: true
service:
  enableRoute: true
usersPassword: odmAdmin