customization:
  runAsUser: ''
  securitySecretRef: default-ingress-cert # Sticky session
decisionCenter:
  enabled: true
  # replicaCount: 1 # default value
  replicaCount: 2
image:
  pullSecrets:
    - my-odm-docker-registry
  repository: cp.icr.io/cp/cp4a/odm
# internalDatabase:
#   persistence:
#     enabled: true
#     useDynamicProvisioning: true
#   populateSampleData: true
#   runAsUser: ''
externalDatabase:
  type: postgresql
  port: 32312
  secretCredentials: odm-db-credentials
  databaseName: ibmclouddb
  serverName: 75b9f0b9-bac9-4192-b2e2-7fad648a53e2.bngflf7f0ktkmkdl3jhg.databases.appdomain.cloud
  populateSampleData: true
license: true
service:
  enableRoute: true
usersPassword: odmAdmin