customization:
  runAsUser: ''
image:
  pullSecrets:
    - my-odm-docker-registry
  repository: cp.icr.io/cp/cp4a/odm
internalDatabase:
  persistence:
    enabled: true
    useDynamicProvisioning: true
  populateSampleData: true
  runAsUser: ''
license: true
service:
  enableRoute: true
usersPassword: odmAdmin