#!/bin/sh
##listofusers = Remy.Choupin@fr.ibm.com p.gervais@fr.ibm.com gpiedeloup@fr.ibm.com mh_genieyz@fr.ibm.com stephane.wacongne@fr.ibm.com sebastien.pomme@fr.ibm.com a.thalamot@fr.ibm.com nicolas.vigogne@fr.ibm.com HGRANGE@fr.ibm.com olivier.planson@fr.ibm.com bertrand.denoix@fr.ibm.com ntissar.draoui@fr.ibm.com francois_ribal@fr.ibm.com ekaterina.vicaire@fr.ibm.com benoit.durand1@fr.ibm.com cyril.collin@fr.ibm.com SAUTEREY@fr.ibm.com haraulte@fr.ibm.com mrabemananjara@fr.ibm.com DROINPY@fr.ibm.com sebastien.brun@fr.ibm.com marc-etienne.julien@fr.ibm.com bblancard@fr.ibm.com ETROJMAN@fr.ibm.com ba.cherif@fr.ibm.com patrick.bonvoisin@fr.ibm.com bernard.romy@fr.ibm.com dan.goga1@fr.ibm.com mighri.marouane@fr.ibm.com fabien.grillon@fr.ibm.com gerard_mandon@fr.ibm.com philippe_nottelet@fr.ibm.com scabarrus@fr.ibm.com yao_assou@fr.ibm.com desire.brival1@fr.ibm.com philippe.marembert@fr.ibm.com alexis.artus@fr.ibm.com benjamin.cotin@fr.ibm.com lianchen@fr.ibm.com salonzo@fr.ibm.com matthias.benda@ibm.com fanta.kromah@fr.ibm.com

# List 1
#for i in Remy.Choupin@fr.ibm.com p.gervais@fr.ibm.com gpiedeloup@fr.ibm.com mh_genieyz@fr.ibm.com stephane.wacongne@fr.ibm.com sebastien.pomme@fr.ibm.com a.thalamot@fr.ibm.com nicolas.vigogne@fr.ibm.com HGRANGE@fr.ibm.com olivier.planson@fr.ibm.com bertrand.denoix@fr.ibm.com ntissar.draoui@fr.ibm.com francois_ribal@fr.ibm.com ekaterina.vicaire@fr.ibm.com benoit.durand1@fr.ibm.com cyril.collin@fr.ibm.com SAUTEREY@fr.ibm.com haraulte@fr.ibm.com mrabemananjara@fr.ibm.com DROINPY@fr.ibm.com sebastien.brun@fr.ibm.com marc-etienne.julien@fr.ibm.com bblancard@fr.ibm.com ETROJMAN@fr.ibm.com ba.cherif@fr.ibm.com patrick.bonvoisin@fr.ibm.com bernard.romy@fr.ibm.com dan.goga1@fr.ibm.com mighri.marouane@fr.ibm.com fabien.grillon@fr.ibm.com gerard_mandon@fr.ibm.com philippe_nottelet@fr.ibm.com scabarrus@fr.ibm.com yao_assou@fr.ibm.com desire.brival1@fr.ibm.com philippe.marembert@fr.ibm.com alexis.artus@fr.ibm.com benjamin.cotin@fr.ibm.com lianchen@fr.ibm.com salonzo@fr.ibm.com matthias.benda@ibm.com fanta.kromah@fr.ibm.com
# List 2
for i in elmhadi.arafa@fr.ibm.com clasquin@fr.ibm.com acramagnac@fr.ibm.com aymeric.douyere@faurecia.com bpratt@us.ibm.com berangere.linuesa@faurecia.com catherine_mathou@fr.ibm.com christophe.sirvain@fr.ibm.com dominique.lacassagne@fr.ibm.com dominique.loiseaux@faurecia.com elmahdi.arafa@fr.ibm.com fabiengri@gmail.com franck.lefevre@digitalairways.com frederic.bosch@soprasteria.com gael.schinkel@faurecia.com georges-henri.moll@fr.ibm.com hghaffarzadeh@fr.ibm.com jean-baptiste.lafage@faurecia.com jose.gascon@faurecia.com laurent.grateau@fr.ibm.com rabema1@yahoo.fr mimoun_lakri@fr.ibm.com nfritz@us.ibm.com norynh.somchit@soprasteria.com olivier.wettel@faurecia.com paul.renault@digitalairways.com rodolphe.fontaine@fr.ibm.com scabarrus@gmail.com f003932@fr.ibm.com vincent.roma@faurecia.com yann.choupeaux@fr.ibm.com
do
	echo $i
	# Alain's Account ID: b6236659cd0c6579ac89c8f2c59d945d
	bx account user-delete $i -c b6236659cd0c6579ac89c8f2c59d945d -f
done
