apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner-main
spec:
  backgroundColor: blue
  color: white
  location: BannerTop
  text: >-
    You are logged on a shared ROVE cluster with OVN and VNI enabled.