kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operators-view
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#first.last@gmail.com'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregate-olm-view